### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by DianaVashti** [DianaVashti/sji-bdl-client#20]

**Comment by spencerdezartsmith** [comment]
Sent!!! Please feel free to edit them. I also left a note to Lisa about being able to use her creativity so long as it stays simple and streamlined. Can we also confirm with her that it is only the mobile side that NEEDS to be complete. If she would like to keep working afterwards on the desktop thats cool but its the mobile side that has to be finished first. @DianaVashti

**Comment by DianaVashti** [comment]
👍
